networks:
  mediastack:
    name: media
    driver: bridge
    ipam:
      driver: default

include:
  - path: 'radarr/docker-compose.radarr.yml'
  - path: 'nebula-sync/docker-compose.nebula-sync.yml'
  - path: 'sonarr/docker-compose.sonarr.yml'
  - path: 'notifarr/docker-compose.notifarr.yml'
  - path: 'watchtower/docker-compose.watchtower.yml'