include:

  - path: 'portainer/docker-compose.portainer.yaml'
  - path: 'radarr/docker-compose.radarr.yaml'
  - path: 'traefik/docker-compose.traefik.yaml'
  - path: 'authentik/docker-compose.authentik.yaml'
  - path: 'bazarr/docker-compose.bazarr.yaml'
  - path: 'crowdsec/docker-compose.crowdsec.yaml'
  - path: 'ddns-updater/docker-compose.ddns-updater.yaml'
  - path: 'filebot/docker-compose.filebot.yaml'
  - path: 'huntarr/docker-compose.huntarr.yaml'
  - path: 'jellyseerr/docker-compose.jellyseerr.yaml'
  - path: 'sonarr/docker-compose.sonarr.yaml'
  - path: 'readarr/docker-compose.readarr.yaml'
  - path: 'qbittorrent/docker-compose.qbittorrent.yaml'
  - path: 'prowlarr/docker-compose.prowlarr.yaml'
  - path: 'sabnzbd/docker-compose.sabnzbd.yaml'

networks:
  mediastack:
    name: mediastack
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET:?err}
        gateway: ${DOCKER_GATEWAY:?err}