services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - /opt/.env
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /opt/radarr/data:/config
      - /mnt/media/:/media
    ports:
      - 7878:7878
    networks:
      - media
    restart: unless-stopped
  radarr-anime:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /opt/radarr-anime/data:/config
      - /mnt/media/:/media
    ports:
      - 7879:7878
    networks:
      - media
    restart: unless-stopped
  radarr4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /opt/radarr4k/data:/config
      - /mnt/media/:/media
    ports:
      - 7877:7878
    networks:
      - media
    restart: unless-stoppe